server:
  port: 9999

spring:
  datasource:
    username: root
    password: 7456
    url: jdbc:mysql:///xdb
  redis:
    port: 6379
    host: localhost

logging:
  level:
   com.qsh: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
  type-aliases-package: com.qsh.*.entity
